# =============================================================================
# Config Sync Module
# =============================================================================
# This module handles synchronization of configuration files to servers,
# separate from infrastructure provisioning.
# =============================================================================

# =============================================================================
# Traefik Dynamic Configuration Files
# =============================================================================

# Auto-generated routes for team VMs (always regenerated by Terraform)
resource "local_file" "traefik_dynamic_auto" {
  count = length(var.teams) > 0 ? 1 : 0

  filename = "${path.module}/${var.secrets_path}/traefik-dynamic-auto.yml"
  content = templatefile("${path.module}/../../templates/traefik/dynamic.yml.tpl", {
    teams  = var.teams
    domain = var.domain
  })
}

# Custom routes file (created once, then ignored by Terraform)
resource "local_file" "traefik_dynamic_custom" {
  count = length(var.teams) > 0 ? 1 : 0

  filename = "${path.module}/${var.secrets_path}/traefik-dynamic-custom.yml"
  content  = <<-EOT
    # =============================================================================
    # Traefik Custom Configuration
    # =============================================================================
    # This file is for your custom routes and configurations.
    # Terraform will NOT overwrite this file after initial creation.
    # Add your custom HTTP/TCP routers, services, and middlewares here.
    # =============================================================================

    # Example custom HTTP router:
    # http:
    #   routers:
    #     my-custom-service:
    #       entryPoints:
    #         - web
    #       rule: "Host(`custom.${var.domain}`)"
    #       service: my-custom-service
    #
    #   services:
    #     my-custom-service:
    #       loadBalancer:
    #         servers:
    #           - url: "http://10.20.0.10:8080"
  EOT

  lifecycle {
    ignore_changes = [content]
  }
}

# =============================================================================
# Sync Team Jump Keys to Bastion
# =============================================================================

resource "null_resource" "sync_team_jump_key_to_bastion" {
  for_each = var.team_jump_keys

  triggers = {
    jump_key_fingerprint = md5(each.value)
    bastion_ip           = var.edge_public_ip
  }

  connection {
    type        = "ssh"
    user        = var.jump_user
    private_key = file(pathexpand(var.jump_private_key_path))
    host        = var.edge_public_ip
  }

  provisioner "remote-exec" {
    inline = [
      "grep -qF '${trimspace(each.value)}' ~/.ssh/authorized_keys || echo '${trimspace(each.value)}' >> ~/.ssh/authorized_keys"
    ]
  }
}

# =============================================================================
# Sync Xray Configuration to Edge VM
# =============================================================================

resource "null_resource" "sync_xray_config" {
  triggers = {
    xray_config_hash = md5(var.xray_config)
    edge_ip          = var.edge_public_ip
  }

  connection {
    type        = "ssh"
    user        = var.jump_user
    private_key = file(pathexpand(var.jump_private_key_path))
    host        = var.edge_public_ip
  }

  provisioner "file" {
    content     = var.xray_config
    destination = "/tmp/xray-config.json"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo mv /tmp/xray-config.json /opt/xray/config.json",
      "sudo systemctl restart xray",
      "echo 'Xray config updated and service restarted'"
    ]
  }
}

# =============================================================================
# Sync Traefik Dynamic Configuration to Edge VM
# =============================================================================

resource "null_resource" "sync_traefik_dynamic_auto" {
  count = var.enable_traefik_sync && length(var.teams) > 0 ? 1 : 0

  triggers = {
    traefik_auto_config_hash = md5(local_file.traefik_dynamic_auto[0].content)
    edge_ip                  = var.edge_public_ip
  }

  connection {
    type        = "ssh"
    user        = var.jump_user
    private_key = file(pathexpand(var.jump_private_key_path))
    host        = var.edge_public_ip
  }

  provisioner "file" {
    content     = local_file.traefik_dynamic_auto[0].content
    destination = "/tmp/traefik-dynamic-auto.yml"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo mv /tmp/traefik-dynamic-auto.yml /opt/traefik/dynamic/auto.yml",
      "sudo chmod 644 /opt/traefik/dynamic/auto.yml",
      "echo 'Traefik auto-generated config updated (will be reloaded automatically)'"
    ]
  }

  depends_on = [local_file.traefik_dynamic_auto]
}

# Sync custom Traefik config (only if doesn't exist on server)
resource "null_resource" "sync_traefik_dynamic_custom" {
  count = var.enable_traefik_sync && length(var.teams) > 0 ? 1 : 0

  triggers = {
    edge_ip = var.edge_public_ip
  }

  connection {
    type        = "ssh"
    user        = var.jump_user
    private_key = file(pathexpand(var.jump_private_key_path))
    host        = var.edge_public_ip
  }

  provisioner "file" {
    content     = local_file.traefik_dynamic_custom[0].content
    destination = "/tmp/traefik-dynamic-custom.yml"
  }

  provisioner "remote-exec" {
    inline = [
      "if [ ! -f /opt/traefik/dynamic/custom.yml ]; then",
      "  sudo mv /tmp/traefik-dynamic-custom.yml /opt/traefik/dynamic/custom.yml",
      "  sudo chmod 644 /opt/traefik/dynamic/custom.yml",
      "  echo 'Traefik custom config created'",
      "else",
      "  rm /tmp/traefik-dynamic-custom.yml",
      "  echo 'Traefik custom config already exists, skipping'",
      "fi"
    ]
  }

  depends_on = [local_file.traefik_dynamic_custom]
}
